joconde_lab_homepage:
    pattern:  /
    defaults: { _controller: JocondeLabBundle:Notice:index }

search_autocomplete:
    pattern: /search_ajax
    defaults: { _controller: JocondeLabBundle:Notice:autocompleteAjax }
    requirements:
        _method: GET
    options:
        expose: true

add_favorite_notice:
    pattern:   /add-notice-favorite
    defaults:  { _controller: JocondeLabBundle:Notice:addfavorite }
    requirements:
        _method: GET
    options:
        expose: true

notice_hover:
    pattern:   /ajax_view
    defaults:  { _controller: JocondeLabBundle:Notice:noticeHover }
    requirements:
        _method: GET
    options:
        expose: true

change_question:
    pattern:   /change_question
    defaults:  { _controller: JocondeLabBundle:Notice:newQuestion }
    requirements:
        _method: GET
    options:
        expose: true

change_question_good:
    pattern:   /change_question_good
    defaults:  { _controller: JocondeLabBundle:Notice:goodQuestion }
    requirements:
        _method: GET
    options:
        expose: true

notice_id:
    pattern:   /notice/{id}
    defaults:  { _controller: JocondeLabBundle:Notice:notice }
    requirements:
        _method: GET
    options:
        expose: true

favorite_notice:
    pattern:  /a-voir-plus-tard
    defaults: { _controller: JocondeLabBundle:Notice:favorite }