joconde_lab_homepage:
    pattern:  /
    defaults: { _controller: JocondeLabBundle:Notice:index }

search_autocomplete:
    pattern: /search_ajax
    defaults: { _controller: JocondeLabBundle:Notice:autocompleteAjax }
    requirements:
        _method: GET
    options:
        expose: true

add_favorite_notice:
    pattern:   /add-notice-favorite/{id}
    defaults:  { _controller: JocondeLabBundle:Notice:addfavorite }

notice_id:
    pattern:   /notice/{id}
    defaults:  { _controller: JocondeLabBundle:Notice:notice }