parameters:
#    joconde_lab.example.class: Joconde\LabBundle\Example

services:
#    joconde_lab.example:
#        class: %joconde_lab.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
